### PR TITLE
Add support for Python 3.8, drop 3.4

### PR DESCRIPTION
**Pull request by mgedmin**

### CODE REVIEW

**Comment by jugmac00** [comment]
While https://github.com/zopefoundation/zope.formlib/issues/28 was broken, it showed that the Travis test are not super meaningful.

I hope I do not get it wrong, but it looked like Travis was green, while Tox was red - for the same code. The difference was that tox built a package and and travis just tested the checked out code.

Why not let travis run the tox tests?

**Comment by mgedmin** [comment]
> While #28 was broken, it showed that the Travis tests are not super meaningful.

Well, they catch most problems, just not that particular one.  If we didn't pass `-e` to `pip install` in our .travis.yml, we'd have caught the problem too.  (The price is coverage measurement might get confused about paths, maybe fail to merge the coverage numbers for the same module correctly?)

> Why not let Travis run the tox tests?

tox currently doesn't measure test coverage.  Travis does.  This is not an unsurmountable problem -- many other zopefoundation packages measure coverage from tox.

Personally, I'd rather run check-manifest before making a release (it integrates with zest.releaser automatically, if both are installed in the same virtualenv), instead of wrangling with coverage path resolution intricacies _again_.  But if you wish to prepare a merge request to make travis use tox (https://pypi.org/project/tox-travis/ is useful here), I'd be happy to review it.

**Comment by jugmac00** [comment]
Ok, thanks, I did not know about the coverage issues.

After I saw dozens of "why did the coverage drop after I changed a txt/pt/other unrelated file" in the Zope projects, I decided not to use coveralls or similar for my projects, and just run coverage locally with my tests.

There are so many valid combinations out there what and when to run your tools - your ide, pre-commit, tox, ci ... I am still experimenting what is the best combination for myself.

There is just one fixed goal - do not depend on not forgetting to run something manually.

So lately, I started to use `pre-commit` hooks for more and more linters/tools.

`check-manifest` and `pre-commit` are a great combo :-)

P.S.: Instead of `tox-travis` I just use `tox -e py` and it works - at least for my projects at work.

**Comment by d-maurer** [comment]
Marius Gedminas wrote at 2020-2-26 23:55 -0800:
> ...
>Personally, I'd rather run check-manifest before making a release

If the proper `setuptools-git` integration module is available,
then the manifest file is updated automatically based on which files are
managed via "git" when `setup.py` builds the release.
I prefer such an automatic update over manual modifications.

**Pull request merged**
